<?php

    const EXC_CODE_SOCKET_API_CONNECTION_FAIL   = 9999; # When opening a socket to api host return false
    const EXC_CODE_NOT_REGISTERED               = 1000; # When api session register control return false
    const EXC_CODE_REGISTER_FAIL                = 1001; # When api session registering return false
    const EXC_CODE_VEHICLES_FETCH_FAIL          = 1002; # When attempt to fetch all vehicles return false
    const EXC_CODE_VEHICLES_PULL_FAIL           = 1003; # When attempt to pull some vehicles return false
    const EXC_CODE_FLEETS_PULL_FAIL             = 1004; # When attempt to fetch all fleets of vehicle return false
    const EXC_CODE_RESERVATIONS_FETCH_FAIL      = 1005; # When attempt to fetch all return false
    const EXC_CODE_RESERVATIONS_PULL_FAIL       = 1006; # When attempt to pull some return false
    const EXC_CODE_RESERVATIONS_PUSH_FAIL       = 1007; # When attempt to push return false
    const EXC_CODE_RESERVATIONS_UPDATE_FAIL     = 1008; # When attempt to update return false
    const EXC_CODE_PROVINCES_FETCH_FAIL         = 1009; # When attempt to fetch all provinces return false
    const EXC_CODE_PROVINCES_PULL_FAIL          = 1010; # When attempt to pull some provinces return false
    const EXC_CODE_COUNTIES_FETCH_FAIL          = 1011; # When attempt to fetch counties return false
    const EXC_CODE_ROAD_COST_FETCH_FAIL         = 1012; # When attempt to fetch road cost return false

?>